-- Population Census
-- Categories: Basic Join

SELECT
    SUM(CITY.POPULATION) AS TOTAL_POPULATION
FROM
    COUNTRY
INNER JOIN CITY
ON
    COUNTRY.CODE = CITY.COUNTRYCODE
WHERE
    COUNTRY.CONTINENT = 'Asia';
