-- Weather Observation Station 17
-- Categories: Aggregation

SELECT
    ROUND(LONG_W, 4) AS LONG_W
FROM
    STATION
WHERE
    ROUND(LAT_N, 4) IN (SELECT ROUND(MIN(INNER_TABLE.LAT_N), 4) FROM STATION AS INNER_TABLE WHERE ROUND(INNER_TABLE.LAT_N, 4) > 38.7880);
